### ISSUE TITLE
short name is confusing

### ISSUE THREAD

**Issue by tstaerk** [Cyclenerd/sap-on-gcp-scripts#1]
Nils,

I think this repository is 99% perfect, so, please do not wonder if I "complain about the small stuff". I am just following your instructions and want to preserve everything that confuses me, otherwise I will forget once I succeed.

First thing that confuses me is in your README:

```
# Change short name to quickly separate everything
echo "MY_GCP_SHORT_NAME=random-name-123" >> config

```
could you clarify in the README if the short name is just the project name or if it will be prefixed to other things as well?
Maybe it would be easiest to call it MY_GCP_PROJECT_NAME.

just an idea :)

**Comment by Cyclenerd** [comment]
Hi,

Thank you for your feedback. I tried clarified it with commit https://github.com/Cyclenerd/sap-on-gcp-scripts/commit/37dd5c5b34e7fce4706b493fe320d79b3244bd20

To make everything work you only have to change the variable `MY_GCP_SHORT_NAME`. This will generate the default project name/ID (`MY_GCP_PROJECT`), network name and the globally unique storage bucket name.

Hope this makes everything even easier.

Have fun 👍
